/**
 * Renders api/skills/builtin/wiki-authoring/SKILL.md into a TypeScript constant module.
 *
 * The build bundles api/ into a single file, after which no markdown under api/skills
 * is reachable on disk. Inlining the baseline at build time removes that dependency.
 */
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseSkillMarkdown } from '../skills/skill-parser.js';

const MODULE_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.join(MODULE_DIR, '..', '..', '..');

export const WIKI_AUTHORING_SKILL_PATH = path.join(
  REPO_ROOT, 'api', 'skills', 'builtin', 'wiki-authoring', 'SKILL.md',
);

export const WIKI_AUTHORING_BUNDLE_PATH = path.join(
  REPO_ROOT, 'api', 'services', 'wiki', 'generated', 'wiki-authoring-builtin.ts',
);

export function renderWikiAuthoringBundle(rawSkillMd: string): string {
  const { frontmatter, body } = parseSkillMarkdown(rawSkillMd);
  const trimmed = body.trim();
  if (!trimmed) {
    throw new Error('wiki-authoring SKILL.md has an empty body.');
  }

  const version = typeof frontmatter.version === 'string' && frontmatter.version.trim()
    ? frontmatter.version.trim()
    : '0.0.0';
  const digest = createHash('sha256').update(rawSkillMd, 'utf8').digest('hex');

  return [
    '/* eslint-disable */',
    '// AUTO-GENERATED by scripts/generate-wiki-skill-bundle.ts — do not edit by hand.',
    '// Source: api/skills/builtin/wiki-authoring/SKILL.md',
    '',
    `export const WIKI_AUTHORING_BUILTIN_VERSION = ${JSON.stringify(version)};`,
    '',
    `export const WIKI_AUTHORING_BUILTIN_DIGEST = ${JSON.stringify(digest)};`,
    '',
    `export const WIKI_AUTHORING_BUILTIN_BODY = ${JSON.stringify(trimmed)};`,
    '',
  ].join('\n');
}
