import type { AgentProfile } from '../contracts.js';
import { SYNAX_AGENT_PROFILE_ID } from './synax-session-mode.js';

export const synaxAgentProfile: AgentProfile = {
  id: SYNAX_AGENT_PROFILE_ID,
  label: 'Synax Agent',
  kind: 'executor',
  mode: 'primary',
  description: 'General-purpose agent that adapts to user intent and delegates specialized work.',
  defaultThinkingMode: 'standard',
  allowedCapabilities: [
    'bash',
    'file.read',
    'file.glob',
    'file.list',
    'grep.search',
    'diff.read',
    'file.write',
    'file.patch',
    'file.delete',
    'wiki.get_snapshot',
    'wiki.get_tree',
    'wiki.search_content',
    'wiki.search_batch',
    'wiki.read_document',
    'wiki.read_section',
    'wiki.get_references',
    'task.create',
    'task.update',
    'task.get',
    'task.list',
    'subagent.delegate',
    'skill.load',
    'tools.escalate',
    'agent.adapt',
  ],
  permissionDefaults: [
    { gate: 'read', pattern: '*', action: 'allow', reason: 'Synax agent reads freely.' },
    { gate: 'write', pattern: '*', action: 'ask', reason: 'Writes require approval.' },
    { gate: 'delete', pattern: '*', action: 'ask', reason: 'Deletes require approval.' },
    { gate: 'shell', pattern: '*', action: 'ask', reason: 'Shell execution requires approval.' },
    { gate: 'task', pattern: '*', action: 'ask', reason: 'Task delegation requires approval.' },
  ],
  defaultSkills: ['action-executor'],
  maxSteps: 64,
  status: 'active',
  toolPolicy: { allowParallelReadTools: true, allowSubtasks: true, maxParallelReadTools: 4 },
  loopHints: [
    'Understand user intent before acting.',
    'For architecture or design questions, prefer wiki.search_batch or wiki.search_content (FTS), then wiki.read_section over raw code grep.',
    'For multi-step work, create a session TODO early with task.create and keep it current via task.update.',
    'For exploration intent, delegate immediately to subagent.delegate(profileId: "explorer") instead of wide serial searches.',
    'Delegate structured review to subagent.delegate(profileId: "reviewer").',
    'For sustained planning, exploration, or review work, call agent.adapt with the matching variant.',
    'Prefer minimal, verifiable steps and concrete evidence.',
  ],
  allowsSubsessions: true,
};
