import { skillSourceService } from './api/services/skills/skill-source-service.js';
import { ensureSynaxAgentRegistered } from './api/services/agent-runtime/synax/index.js';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { Hono } from 'hono';
import { serve } from '@hono/node-server';
import { DATA_ROOT } from './api/lib/env.js';
import { agentRuntimeRoutes } from './api/routes/agent-runtime.js';
import { agentSessionRuntime } from './api/services/agent-runtime/session-runtime.js';
import { agentRuntimeStore } from './api/services/agent-runtime/session-store.js';
import { getRawSqlite } from './api/db/index.js';
import { listTurnReferenceOptions, prepareTurnReferences } from './api/services/agent-runtime/turn-references.js';
import { activeTurnReferences, effectiveTurnMcpIds } from './api/services/agent-runtime/turn-reference-state.js';
import { acceptRuntimeRun, activateAcceptedRun } from './api/services/agent-runtime/run-admission.js';
import { inputQueueService } from './api/services/agent-runtime/input-queue-service.js';
import { updateProjectSettings } from './api/lib/config/project-settings-store.js';
import { mcpClientManager } from './api/services/mcp/mcp-client-manager.js';
import { warmupMcpForSession, mcpSessionToolProvider } from './api/services/mcp/mcp-session-tool-provider.js';
const root=path.join(DATA_ROOT,'workspace'); fs.mkdirSync(path.join(root,'.synax/skills/layout-review'),{recursive:true});
fs.writeFileSync(path.join(root,'README.md'),'# Preview workspace\nKeep controls quiet and input prominent.\n');
fs.writeFileSync(path.join(root,'.env.secret'),'TOKEN=do-not-read');
fs.writeFileSync(path.join(root,'.synax/skills/layout-review/SKILL.md'),'---\nname: layout-review\ndescription: Review the input layout and accessible controls.\n---\nReview spacing, readable contrast and keyboard interaction.');
fs.writeFileSync(path.join(DATA_ROOT,'projects.json'),JSON.stringify([{id:'slash-preview',name:'Preview',source:{kind:'localPath',localPath:root}}]));
const db=getRawSqlite(),stamp=new Date().toISOString();
db.prepare(`INSERT INTO wiki_snapshots (id,project_id,branch,head_commit_sha,working_tree_hash,revision,status,document_ids_json,created_at,created_by) VALUES ('snapshot-preview','slash-preview','main','','',1,'ready','[]',?,'human')`).run(stamp);
db.prepare(`INSERT INTO wiki_documents (id,snapshot_id,project_id,title,doc_type,content_md,created_at,updated_at) VALUES ('wiki-preview','snapshot-preview','slash-preview','输入区设计','module','参考内容：正文在上，工具在下。',?,?)`).run(stamp,stamp);
updateProjectSettings('slash-preview',{mcpServers:[{id:'qa-echo',name:'Echo MCP',enabled:true,command:process.execPath,args:[path.resolve('api/services/mcp/__tests__/fixtures/fake-mcp-server.mjs')]},{id:'disabled',name:'Disabled',enabled:false,command:process.execPath}]},'local-qa');
ensureSynaxAgentRegistered();
skillSourceService.createSource({id:'qa-project',label:'QA project skills',type:'project',enabled:true});
const files=listTurnReferenceOptions('slash-preview','file','README');assert.equal(files.length,1);
assert(!listTurnReferenceOptions('slash-preview','file','.env').length);
const skills=listTurnReferenceOptions('slash-preview','skill','layout-review');assert.equal(skills.length,1);
const wiki=listTurnReferenceOptions('slash-preview','wiki');assert.equal(wiki.length,1);
const mcp=listTurnReferenceOptions('slash-preview','mcp');assert.equal(mcp.length,1);
const session=agentSessionRuntime.create({projectId:'slash-preview',profileId:'synax',backendId:'native',workDir:root,prompt:'Preview task',mcpServerIds:[],sessionMetadata:{mode:'chat'}});
const refs=[files[0],skills[0],wiki[0],mcp[0]];
const ctx=prepareTurnReferences(session.id,refs)!;assert.equal(ctx.references.length,4);assert(ctx.content.includes('Keep controls quiet'));assert(ctx.content.includes('Review spacing'));assert(ctx.content.includes('参考内容'));
for(const bad of [{kind:'file',id:'.env.secret'},{kind:'file',id:'../projects.json'},{kind:'wiki',id:'foreign-wiki'},{kind:'mcp',id:'disabled'}] as const)assert.throws(()=>prepareTurnReferences(session.id,[bad]));
const queued=inputQueueService.enqueue(session.id,{message:'Queued reference',references:refs});assert.equal(queued[0].referenceContext!.references.length,4);assert.equal(inputQueueService.consumeNext(session.id)!.referenceContext!.content,ctx.content);
const admitted=acceptRuntimeRun(session.id,{message:'Use selected references',references:refs},'qa-admission');const saved=(admitted.run.metadata.runtime as any).input.referenceContext;assert.equal(saved.content,ctx.content);
activateAcceptedRun(session.id,admitted.run.id,'preview-trigger',null);agentRuntimeStore.updateRun(admitted.run.id,{metadata:{...agentRuntimeStore.getRun(admitted.run.id).metadata,turnReferences:saved}});agentRuntimeStore.updateSession(session.id,{activeRunId:admitted.run.id});
assert.deepEqual(effectiveTurnMcpIds(session.id),['qa-echo']);await warmupMcpForSession(session.id);assert(mcpSessionToolProvider.getTools(session.id).some(t=>t.id.includes('echo')));
agentRuntimeStore.updateRun(admitted.run.id,{status:'completed'});agentRuntimeStore.updateSession(session.id,{status:'completed',activeRunId:null});assert.equal(activeTurnReferences(session.id),undefined);assert.deepEqual(effectiveTurnMcpIds(session.id),[]);
const next=acceptRuntimeRun(session.id,{message:'No references'},'qa-next');assert.equal((next.run.metadata.runtime as any).input.referenceContext,undefined);
console.log('REFERENCE_SMOKE_PASS: 4 reference kinds, secret/traversal/cross-project/disabled rejection, durable queue/admission snapshots, MCP warmup/tools, next-turn isolation.');
const app=new Hono();app.get('/api/health',c=>c.json({status:'ok'}));app.route('/api/agent-runtime',agentRuntimeRoutes);
serve({fetch:app.fetch,hostname:'127.0.0.1',port:3217});
process.on('SIGTERM',()=>{mcpClientManager.closeAll();process.exit(0)});
