import { normalizeTheme } from "./normalize";
import { DEFAULT_THEME } from "./defaults";
import type { NormalizedTheme } from "./contract";

/**
 * Curated palettes inspired by editor classics. They are intentionally
 * expressed as Synax semantic tokens so each preset remains portable and can
 * evolve independently from component CSS.
 */
const PRESET_DEFINITIONS = [
  {
    version: 1 as const,
    id: "one-dark",
    name: "One Dark",
    description: "A calm graphite canvas with blue and cyan syntax accents.",
    colors: {
      light: {
        canvas: "#fafafa",
        surface: "#ffffff",
        surfaceSecondary: "#f0f1f2",
        text: "#383a42",
        textMuted: "#696c77",
        textSubtle: "#9da1ab",
        border: "#d7dae0",
        borderStrong: "#b9bec8",
        accent: "#4078f2",
        accentForeground: "#ffffff",
        accentSoft: "#e7edff",
        success: "#50a14f",
        warning: "#c18401",
        danger: "#e45649",
        info: "#0184bc",
        input: "#ffffff",
        inputForeground: "#383a42",
        selection: "#d7e2ff",
        focus: "#4078f2",
        tooltip: "#282c34",
        tooltipForeground: "#f8f8f2",
      },
      dark: {
        canvas: "#282c34",
        surface: "#21252b",
        surfaceSecondary: "#2c313a",
        text: "#abb2bf",
        textMuted: "#7f848e",
        textSubtle: "#5c6370",
        border: "#3e4451",
        borderStrong: "#545862",
        accent: "#61afef",
        accentForeground: "#17202b",
        accentSoft: "#263b52",
        success: "#98c379",
        warning: "#e5c07b",
        danger: "#e06c75",
        info: "#56b6c2",
        input: "#21252b",
        inputForeground: "#abb2bf",
        selection: "#3e4e67",
        focus: "#61afef",
        tooltip: "#f8f8f2",
        tooltipForeground: "#282c34",
      },
    },
  },
  {
    version: 1 as const,
    id: "dracula",
    name: "Dracula",
    description: "A nocturnal purple palette with neon pink, cyan, and green.",
    colors: {
      light: {
        canvas: "#f8f7ff",
        surface: "#ffffff",
        surfaceSecondary: "#efedff",
        text: "#302b3d",
        textMuted: "#6f6a82",
        textSubtle: "#9892ad",
        border: "#dcd7ee",
        borderStrong: "#b9add7",
        accent: "#7c3aed",
        accentForeground: "#ffffff",
        accentSoft: "#eee7ff",
        success: "#159957",
        warning: "#b7791f",
        danger: "#d1435b",
        info: "#1677a8",
        input: "#ffffff",
        inputForeground: "#302b3d",
        selection: "#dfd3ff",
        focus: "#7c3aed",
        tooltip: "#282a36",
        tooltipForeground: "#f8f8f2",
      },
      dark: {
        canvas: "#282a36",
        surface: "#21222c",
        surfaceSecondary: "#343746",
        text: "#f8f8f2",
        textMuted: "#b8b8c8",
        textSubtle: "#6272a4",
        border: "#44475a",
        borderStrong: "#6272a4",
        accent: "#bd93f9",
        accentForeground: "#211b2d",
        accentSoft: "#3a2f55",
        success: "#50fa7b",
        warning: "#f1fa8c",
        danger: "#ff5555",
        info: "#8be9fd",
        input: "#21222c",
        inputForeground: "#f8f8f2",
        selection: "#44475a",
        focus: "#bd93f9",
        tooltip: "#f8f8f2",
        tooltipForeground: "#282a36",
      },
    },
  },
  {
    version: 1 as const,
    id: "nord",
    name: "Nord",
    description: "A restrained arctic blue palette for long, focused sessions.",
    colors: {
      light: {
        canvas: "#eceff4",
        surface: "#f8fafc",
        surfaceSecondary: "#e5e9f0",
        text: "#2e3440",
        textMuted: "#5e6878",
        textSubtle: "#8792a5",
        border: "#d8dee9",
        borderStrong: "#b8c2d2",
        accent: "#5e81ac",
        accentForeground: "#ffffff",
        accentSoft: "#e1eaf5",
        success: "#5f8a72",
        warning: "#b27a3d",
        danger: "#bf616a",
        info: "#5e81ac",
        input: "#f8fafc",
        inputForeground: "#2e3440",
        selection: "#c9d7ea",
        focus: "#5e81ac",
        tooltip: "#2e3440",
        tooltipForeground: "#eceff4",
      },
      dark: {
        canvas: "#2e3440",
        surface: "#3b4252",
        surfaceSecondary: "#434c5e",
        text: "#eceff4",
        textMuted: "#d8dee9",
        textSubtle: "#8893a7",
        border: "#4c566a",
        borderStrong: "#616d83",
        accent: "#88c0d0",
        accentForeground: "#24313a",
        accentSoft: "#3a5966",
        success: "#a3be8c",
        warning: "#ebcb8b",
        danger: "#bf616a",
        info: "#81a1c1",
        input: "#3b4252",
        inputForeground: "#eceff4",
        selection: "#4c566a",
        focus: "#88c0d0",
        tooltip: "#eceff4",
        tooltipForeground: "#2e3440",
      },
    },
  },
  {
    version: 1 as const,
    id: "monokai",
    name: "Monokai",
    description: "A high-contrast studio palette with lime, pink, and warm gold.",
    colors: {
      light: {
        canvas: "#f8f8f2",
        surface: "#ffffff",
        surfaceSecondary: "#eeeeea",
        text: "#272822",
        textMuted: "#686861",
        textSubtle: "#989890",
        border: "#d7d7ce",
        borderStrong: "#b7b7aa",
        accent: "#7b8f00",
        accentForeground: "#ffffff",
        accentSoft: "#edf2c9",
        success: "#4f8f00",
        warning: "#b36b00",
        danger: "#c4265e",
        info: "#287b9e",
        input: "#ffffff",
        inputForeground: "#272822",
        selection: "#dfe6a6",
        focus: "#7b8f00",
        tooltip: "#272822",
        tooltipForeground: "#f8f8f2",
      },
      dark: {
        canvas: "#272822",
        surface: "#1f201b",
        surfaceSecondary: "#3e3d32",
        text: "#f8f8f2",
        textMuted: "#c5c8a5",
        textSubtle: "#75715e",
        border: "#49483e",
        borderStrong: "#75715e",
        accent: "#a6e22e",
        accentForeground: "#1f201b",
        accentSoft: "#3e5120",
        success: "#a6e22e",
        warning: "#e6db74",
        danger: "#f92672",
        info: "#66d9ef",
        input: "#1f201b",
        inputForeground: "#f8f8f2",
        selection: "#49483e",
        focus: "#a6e22e",
        tooltip: "#f8f8f2",
        tooltipForeground: "#272822",
      },
    },
  },
  {
    version: 1 as const,
    id: "solarized",
    name: "Solarized",
    description: "A low-contrast, warm-cool palette tuned for sustained reading.",
    colors: {
      light: {
        canvas: "#fdf6e3",
        surface: "#eee8d5",
        surfaceSecondary: "#e5dfcc",
        text: "#586e75",
        textMuted: "#657b83",
        textSubtle: "#93a1a1",
        border: "#d6cfbc",
        borderStrong: "#b9b19c",
        accent: "#268bd2",
        accentForeground: "#fdf6e3",
        accentSoft: "#d7ebf9",
        success: "#859900",
        warning: "#b58900",
        danger: "#dc322f",
        info: "#2aa198",
        input: "#fdf6e3",
        inputForeground: "#586e75",
        selection: "#c7e3f5",
        focus: "#268bd2",
        tooltip: "#073642",
        tooltipForeground: "#fdf6e3",
      },
      dark: {
        canvas: "#002b36",
        surface: "#073642",
        surfaceSecondary: "#0b3b46",
        text: "#839496",
        textMuted: "#93a1a1",
        textSubtle: "#657b83",
        border: "#1b4d57",
        borderStrong: "#2d6872",
        accent: "#268bd2",
        accentForeground: "#fdf6e3",
        accentSoft: "#124b62",
        success: "#859900",
        warning: "#b58900",
        danger: "#dc322f",
        info: "#2aa198",
        input: "#073642",
        inputForeground: "#839496",
        selection: "#1b4d57",
        focus: "#268bd2",
        tooltip: "#fdf6e3",
        tooltipForeground: "#002b36",
      },
    },
  },
] as const;

export const BUILTIN_THEMES: readonly NormalizedTheme[] = [
  DEFAULT_THEME,
  ...PRESET_DEFINITIONS.map((definition) => normalizeTheme(definition)),
];

export function getBuiltinTheme(id: string): NormalizedTheme | null {
  return BUILTIN_THEMES.find((theme) => theme.id === id) ?? null;
}
