import { useLocale } from '../../../hooks/useLocale'

const zh = {
  title: '创建工作区',
  intro: '将相关项目放在一起，在同一个会话中协作。',
  workspaceName: '工作区名称',
  namePlaceholder: '例如：产品研发',
  sources: '添加项目',
  local: '本地目录',
  existing: '已有项目',
  browse: '浏览',
  browseTitle: '选择项目目录',
  browseHint: '可一次选择多个目录',
  singleBrowseHint: '浏览并选择一个项目目录',
  path: '项目目录路径',
  add: '添加',
  search: '搜索名称或路径',
  noProjects: '暂无可添加的已有项目',
  noMatches: '没有匹配的项目',
  loading: '正在读取已有项目…',
  retry: '重试',
  included: '已加入',
  members: '工作区项目',
  emptyTitle: '从一个项目开始',
  emptyHint: '选择目录或已有项目，相关项目也可以稍后加入。',
  primary: '默认项目',
  makePrimary: '设为默认',
  remove: '移除',
  primaryHint: '会话从默认项目开始，各项目独立管理分支与提交。',
  count: '已选择 {count} 个项目',
  cancel: '取消',
  close: '关闭',
  creating: '创建中…',
  pickerTitle: '选择工作区项目',
  pickerConfirm: '添加所选项目',
  limit: '一个工作区最多支持 50 个项目。',
  duplicate: '此目录已在工作区中。',
  manage: '工作区项目',
  manageHint: '在同一会话中协作，保留各项目的独立目录。',
  addProject: '添加项目',
  confirmAdd: '加入工作区',
  projectName: '项目名称（可选）',
  nextRun: '项目变更将在下一次会话执行时生效。',
  unlinkHint: '移除项目仅解除关联，磁盘文件会保留。',
  available: '可用',
  missing: '目录缺失',
  noRoots: '尚未配置项目目录。',
  noReferences: '添加相关项目，让会话同时处理前端、服务端或共享组件。',
  refresh: '刷新项目目录和工作区列表',
  loadingWorkspace: '正在加载工作区…',
  added: '项目已加入工作区。',
  removed: '项目已移除，磁盘文件已保留。',
  loadError: '加载项目目录失败',
  projectsError: '加载已有项目失败',
  addError: '添加项目失败',
  removeError: '移除项目失败',
  browseError: '选择目录失败',
  unknownError: '请重试。',
  existingHint: '仅加入所选工作区的默认项目。'
}
const en: Record<keyof typeof zh, string> = {
  title: 'Create workspace',
  intro: 'Bring related projects together and work across them in one session.',
  workspaceName: 'Workspace name',
  namePlaceholder: 'e.g. Product development',
  sources: 'Add projects',
  local: 'Local directory',
  existing: 'Existing projects',
  browse: 'Browse',
  browseTitle: 'Choose project directories',
  browseHint: 'Select one or several directories',
  singleBrowseHint: 'Browse and choose a project directory',
  path: 'Project directory path',
  add: 'Add',
  search: 'Search names or paths',
  noProjects: 'No existing projects available',
  noMatches: 'No matching projects',
  loading: 'Loading existing projects…',
  retry: 'Retry',
  included: 'Added',
  members: 'Workspace projects',
  emptyTitle: 'Start with a project',
  emptyHint:
    'Choose a directory or an existing project. Add related projects anytime.',
  primary: 'Default project',
  makePrimary: 'Set as default',
  remove: 'Remove',
  primaryHint:
    'Sessions start in the default project. Each project keeps its own branches and commits.',
  count: '{count} projects selected',
  cancel: 'Cancel',
  close: 'Close',
  creating: 'Creating…',
  pickerTitle: 'Choose workspace projects',
  pickerConfirm: 'Add selected projects',
  limit: 'A workspace supports up to 50 projects.',
  duplicate: 'This directory is already in the workspace.',
  manage: 'Workspace projects',
  manageHint:
    'Work across projects in one session, with a separate directory for each.',
  addProject: 'Add project',
  confirmAdd: 'Add to workspace',
  projectName: 'Project name (optional)',
  nextRun: 'Project changes take effect on the next session execution.',
  unlinkHint:
    'Removing a project only unlinks it. Files on disk are preserved.',
  available: 'Available',
  missing: 'Directory missing',
  noRoots: 'No project directories configured yet.',
  noReferences:
    'Add related projects to work across your frontend, services, or shared libraries.',
  refresh: 'Refresh project directories and workspaces',
  loadingWorkspace: 'Loading workspace…',
  added: 'Project added to the workspace.',
  removed: 'Project removed. Files on disk are preserved.',
  loadError: 'Failed to load project directories',
  projectsError: 'Failed to load existing projects',
  addError: 'Failed to add project',
  removeError: 'Failed to remove project',
  browseError: 'Failed to choose directory',
  unknownError: 'Please retry.',
  existingHint: 'Only the selected workspace’s default project is added.'
}
export type WorkspaceCopy = typeof en
export function useWorkspaceCopy(): WorkspaceCopy {
  return useLocale().locale === 'zh' ? zh : en
}

/** Only normalize separators on Windows paths; POSIX paths may contain backslashes. */
export function workspacePathKey(path: string): string {
  const trimmed = path.trim()
  const normalized = /^[a-z]:[\\/]|^\\\\/i.test(trimmed)
    ? trimmed.replace(/\\/g, '/')
    : trimmed
  return normalized.replace(/\/+$/, '') || '/'
}
