import { randomUUID } from 'node:crypto';
import { getRawSqlite } from '../../db/index.js';
import { getGlobalConfigForRuntime } from '../../lib/config/config-store.js';
import { createAsset, getAsset, sessionHasAsset } from '../agent-runtime/media-assets.js';
import { assertSessionMediaBudget } from '../agent-runtime/tools/media-context.js';
import { modalityForMime } from '../agent-runtime/content-parts.js';
import { saveGeneratedMedia } from '../agent-runtime/generated-media.js';
import { agentRuntimeStore } from '../agent-runtime/session-store.js';
import { sessionLiveBus } from '../agent-runtime/session-live-bus.js';
import type { MediaJob, MediaJobInput, MediaJobStatus } from './contracts.js';
import { mediaJobInputSchema } from './schema.js';
import { findMediaModel } from './catalog.js';
import { cancelMediaJob, pollMediaJob, submitMediaJob } from './adapters.js';

const MAX_VIDEO_OUTPUT = 500 * 1024 * 1024;
const rowToJob = (r:any):MediaJob=>({id:r.id,sessionId:r.session_id,input:JSON.parse(r.input_json),status:r.status,upstreamId:r.upstream_id||undefined,resultAssetIds:JSON.parse(r.result_asset_ids_json||'[]'),errorCode:r.error_code||undefined,error:r.error||undefined,createdAt:r.created_at,updatedAt:r.updated_at,cancellationSupported:true});
function row(id:string){return getRawSqlite().prepare('SELECT * FROM media_jobs WHERE id=?').get(id) as any;}
export function getMediaJob(id:string){const r=row(id);return r?rowToJob(r):undefined;}
export function listMediaJobs(sessionId:string,limit=50){return (getRawSqlite().prepare('SELECT * FROM media_jobs WHERE session_id=? ORDER BY created_at DESC LIMIT ?').all(sessionId,limit) as any[]).map(rowToJob);}
function update(id:string,patch:Record<string,any>){const keys=Object.keys(patch);if(!keys.length)return;const values=keys.map(k=>patch[k]);getRawSqlite().prepare(`UPDATE media_jobs SET ${keys.map(k=>`${k}=?`).join(',')}, updated_at=? WHERE id=?`).run(...values,new Date().toISOString(),id);}
export function createMediaJob(sessionId:string,projectId:string,raw:unknown){const input=mediaJobInputSchema.parse(raw) as MediaJobInput;input.projectId=projectId;const model=findMediaModel(getGlobalConfigForRuntime(), input.providerId, input.modelId);if(!model.capabilities.operations.includes(input.operation)) throw new Error(`Model '${input.modelId}' does not support ${input.operation}.`);if(input.operation.includes('image-to') && !input.references?.length) throw new Error('An image reference is required for image-to-media generation.');if(input.references?.length){assertSessionMediaBudget(sessionId,input.references.map(r=>r.assetId));for(const ref of input.references)if(!sessionHasAsset(sessionId,ref.assetId))throw new Error('Media is not attached to this session.');}const now=new Date().toISOString();const existing=getRawSqlite().prepare('SELECT * FROM media_jobs WHERE session_id=? AND idempotency_key=?').get(sessionId,input.idempotencyKey) as any;if(existing)return rowToJob(existing);const id=`mjob_${randomUUID().replaceAll('-','')}`;getRawSqlite().prepare('INSERT INTO media_jobs (id,session_id,project_id,provider_id,model_id,operation,input_json,idempotency_key,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(id,sessionId,projectId,input.providerId,input.modelId,input.operation,JSON.stringify(input),input.idempotencyKey,'queued',now,now);void executeMediaJob(id);return getMediaJob(id)!;}
async function executeMediaJob(id:string){const r=row(id);if(!r||['succeeded','failed','cancelled','unknown'].includes(r.status))return;const input=JSON.parse(r.input_json) as MediaJobInput;const config=getGlobalConfigForRuntime();try {update(id,{status:'submitting',lease_until:Date.now()+120_000});const submitted=await submitMediaJob(config,input);if(submitted.immediate?.length){const assets=[] as string[];for(const file of submitted.immediate){const a=await createAsset(r.project_id,file.filename,file.bytes,file.mediaType);assets.push(a.id);}update(id,{status:'succeeded',result_asset_ids_json:JSON.stringify(assets),lease_until:0});publish(r,assets);return;}update(id,{status:submitted.status,upstream_id:submitted.upstreamId||null,lease_until:0});if(submitted.upstreamId)void pollLoop(id);}catch(e){update(id,{status:'failed',error:String(e instanceof Error?e.message:e),error_code:'MEDIA_PROVIDER_ERROR',lease_until:0});publish(r,[]);}}
async function pollLoop(id:string){for(let i=0;i<120;i++){const r=row(id);if(!r||r.status==='cancelled')return;await new Promise(resolve=>setTimeout(resolve,Math.min(30_000,2000+i*500)));try{const p=await pollMediaJob(getGlobalConfigForRuntime(),JSON.parse(r.input_json),r.upstream_id);if(p.status==='running')continue;if(p.status==='failed'){update(id,{status:'failed',error:p.error||'Media provider task failed.',error_code:'MEDIA_TASK_FAILED'});publish(r,[]);return;}if(p.bytes){if(p.bytes.length>MAX_VIDEO_OUTPUT)throw new Error('Generated video exceeds 500 MiB.');const a=await createAsset(r.project_id,`generated-${id}.mp4`,p.bytes,p.mediaType||'video/mp4');update(id,{status:'succeeded',result_asset_ids_json:JSON.stringify([a.id]),lease_until:0});publish(r,[a.id]);return;}}catch(e){update(id,{status:'failed',error:String(e instanceof Error?e.message:e),error_code:'MEDIA_POLL_FAILED'});publish(r,[]);return;}}update(id,{status:'unknown',error:'Provider task polling window expired.',error_code:'MEDIA_TASK_EXPIRED'});}
function publish(r:any,assetIds:string[]){try{if(assetIds.length){const parts=assetIds.map(id=>({type:modalityForMime(getAsset(id,r.project_id).mediaType),assetId:id}));agentRuntimeStore.appendMessage({id:`media-${r.id}`,sessionId:r.session_id,runId:null,stepId:null,role:'assistant',content:'',contentParts:parts,metadata:{mediaJobId:r.id},createdAt:new Date().toISOString()});}sessionLiveBus.emit(r.session_id,{type:'media_job',jobId:r.id,status:assetIds.length?'succeeded':row(r.id)?.status,resultAssetIds:assetIds});}catch{}}
export async function cancelJob(id:string){const r=row(id);if(!r)return undefined;if(['succeeded','failed','cancelled','unknown'].includes(r.status))return rowToJob(r);if(r.upstream_id)await cancelMediaJob(getGlobalConfigForRuntime(),JSON.parse(r.input_json),r.upstream_id).catch(()=>{});update(id,{status:'cancelled',error:'Cancelled by user.',error_code:'MEDIA_CANCELLED',lease_until:0});return getMediaJob(id);}
export function recoverMediaJobs(){const rows=getRawSqlite().prepare("SELECT id FROM media_jobs WHERE status IN ('queued','submitting','running','downloading')").all() as any[];for(const r of rows)void executeMediaJob(r.id);return rows.length;}
