import { useLocale } from "../../shared/hooks/useLocale";

const zh = {
  title: "新建工作区",
  createWorkspace: "创建工作区",
  manageWorkspace: "管理工作区",
  workspaceMore: "工作区操作",
  backWorkspace: "返回工作区",
  projects: "项目",
  projectCount: "{count} 个项目",
  folderHint: "选择现有项目目录，文件会保留在原位置。",
  confirmRemove: "确认移除",
  removePrompt: "从工作区移除 {name}？",
  removing: "移除中…",
  adding: "加入中…",
  reselect: "重新选择",
  unlinkDetails: "仅解除工作区关联，项目目录、Git 数据和已有会话会保留。",
  intro: "将相关项目放在一起，在同一个会话中协作。",
  workspaceName: "工作区名称",
  namePlaceholder: "例如：产品研发",
  sources: "源文件夹",
  sourceTypes: "来源类型",
  local: "本地",
  remote: "远程",
  remoteTitle: "连接远程主机",
  remoteDescription: "SSH 主机连接功能即将支持。",
  remoteComingSoon: "即将支持",
  localHost: "本地",
  wslDistribution: "WSL2 发行版",
  environmentMismatch:
    "同一工作区只能包含 本地目录，或同一个 WSL2 发行版中的目录。",
  existing: "已有项目",
  path: "项目目录路径",
  add: "添加",
  chooseFolder: "选择文件夹",
  manualPath: "手动输入路径",
  search: "搜索名称或路径",
  noProjects: "暂无可添加的已有项目",
  noMatches: "没有匹配的项目",
  loading: "正在读取已有项目…",
  retry: "重试",
  included: "已加入",
  members: "工作区项目",
  emptyTitle: "从一个项目开始",
  emptyHint: "选择目录或已有项目，相关项目也可以稍后加入。",
  primary: "默认项目",
  makePrimary: "设为默认",
  remove: "移除",
  primaryHint: "会话从默认项目开始，各项目独立管理分支与提交。",
  count: "已选择 {count} 个项目",
  cancel: "取消",
  close: "关闭",
  creating: "创建中…",
  pickerTitle: "选择工作区项目",
  pickerConfirm: "添加所选项目",
  limit: "一个工作区最多支持 50 个项目。",
  duplicate: "此目录已在工作区中。",
  manage: "工作区项目",
  manageHint: "在同一会话中协作，保留各项目的独立目录。",
  addProject: "添加项目",
  confirmAdd: "加入工作区",
  projectName: "项目名称（可选）",
  nextRun: "项目变更将在下一次会话执行时生效。",
  unlinkHint: "移除项目仅解除关联，磁盘文件会保留。",
  available: "可用",
  missing: "目录缺失",
  noRoots: "尚未配置项目目录。",
  noReferences: "添加相关项目，让会话同时处理前端、服务端或共享组件。",
  refresh: "刷新项目目录和工作区列表",
  loadingWorkspace: "正在加载工作区…",
  added: "项目已加入工作区。",
  removed: "项目已移除，磁盘文件已保留。",
  loadError: "加载项目目录失败",
  projectsError: "加载已有项目失败",
  addError: "添加项目失败",
  removeError: "移除项目失败",
  browseError: "选择目录失败",
  unknownError: "请重试。",
  existingHint: "仅加入所选工作区的默认项目。",
};
const en: Record<keyof typeof zh, string> = {
  title: "Create workspace",
  createWorkspace: "Create workspace",
  manageWorkspace: "Manage workspace",
  workspaceMore: "Workspace actions",
  backWorkspace: "Back to workspace",
  projects: "Projects",
  projectCount: "{count} projects",
  folderHint: "Choose an existing project folder. Files stay in their current location.",
  confirmRemove: "Confirm removal",
  removePrompt: "Remove {name} from this workspace?",
  removing: "Removing…",
  adding: "Adding…",
  reselect: "Choose another folder",
  unlinkDetails: "Only the workspace association is removed. Project files, Git data and existing sessions are preserved.",
  intro: "Bring related projects together and work across them in one session.",
  workspaceName: "Workspace name",
  namePlaceholder: "e.g. Product development",
  sources: "Source folders",
  sourceTypes: "Source type",
  local: "Local",
  remote: "Remote",
  remoteTitle: "Connect to a remote host",
  remoteDescription: "SSH host connections are coming soon.",
  remoteComingSoon: "Coming soon",
  localHost: "Local",
  wslDistribution: "WSL2 distribution",
  environmentMismatch:
    "A workspace must use local directories or one WSL2 distribution, not a mixture.",
  existing: "Existing projects",
  path: "Project directory path",
  add: "Add",
  chooseFolder: "Choose folder",
  manualPath: "Enter a path",
  search: "Search names or paths",
  noProjects: "No existing projects available",
  noMatches: "No matching projects",
  loading: "Loading existing projects…",
  retry: "Retry",
  included: "Added",
  members: "Workspace projects",
  emptyTitle: "Start with a project",
  emptyHint:
    "Choose a directory or an existing project. Add related projects anytime.",
  primary: "Default project",
  makePrimary: "Set as default",
  remove: "Remove",
  primaryHint:
    "Sessions start in the default project. Each project keeps its own branches and commits.",
  count: "{count} projects selected",
  cancel: "Cancel",
  close: "Close",
  creating: "Creating…",
  pickerTitle: "Choose workspace projects",
  pickerConfirm: "Add selected projects",
  limit: "A workspace supports up to 50 projects.",
  duplicate: "This directory is already in the workspace.",
  manage: "Workspace projects",
  manageHint:
    "Work across projects in one session, with a separate directory for each.",
  addProject: "Add project",
  confirmAdd: "Add to workspace",
  projectName: "Project name (optional)",
  nextRun: "Project changes take effect on the next session execution.",
  unlinkHint:
    "Removing a project only unlinks it. Files on disk are preserved.",
  available: "Available",
  missing: "Directory missing",
  noRoots: "No project directories configured yet.",
  noReferences:
    "Add related projects to work across your frontend, services, or shared libraries.",
  refresh: "Refresh project directories and workspaces",
  loadingWorkspace: "Loading workspace…",
  added: "Project added to the workspace.",
  removed: "Project removed. Files on disk are preserved.",
  loadError: "Failed to load project directories",
  projectsError: "Failed to load existing projects",
  addError: "Failed to add project",
  removeError: "Failed to remove project",
  browseError: "Failed to choose directory",
  unknownError: "Please retry.",
  existingHint: "Only the selected workspace’s default project is added.",
};
export type WorkspaceCopy = typeof en;
export function useWorkspaceCopy(): WorkspaceCopy {
  return useLocale().locale === "zh" ? zh : en;
}

/** Only normalize separators on Windows paths; POSIX paths may contain backslashes. */
export function workspacePathKey(path: string): string {
  const trimmed = path.trim();
  const normalized = /^[a-z]:[\\/]|^\\\\/i.test(trimmed)
    ? trimmed.replace(/\\/g, "/")
    : trimmed;
  return normalized.replace(/\/+$/, "") || "/";
}
