import { useLocale } from '../../../../hooks/useLocale'
const zh = {
  settings: '设置',
  extensions: '扩展',
  general: '常规设置',
  archive: '会话归档',
  project: '项目设置',
  tool: '工具',
  skill: '技能',
  mcp: 'MCP',
  market: '市场',
  toolHint: '管理 Agent 在当前项目中可以调用的工具。',
  skillHint: '为当前项目添加可复用的知识和工作方式。',
  mcpHint: '连接当前项目需要的外部服务。',
  marketHint: '从内置、本机和远程来源发现扩展。',
  custom: '自定义',
  create: '新建扩展',
  edit: '编辑',
  save: '保存',
  cancel: '取消',
  close: '关闭',
  search: '搜索名称或用途…',
  clear: '清空搜索',
  allKinds: '所有类型',
  allSources: '所有来源',
  source: '来源',
  sources: '管理来源',
  local: '本机发现',
  builtin: 'Synax 内置',
  installed: '已安装',
  toggle: '启用',
  enabled: '已启用',
  disabled: '已关闭',
  install: '安装',
  uninstall: '卸载',
  more: '更多操作',
  refresh: '刷新',
  previous: '上一页',
  next: '下一页',
  loading: '正在加载…',
  empty: '这里还没有扩展',
  noResults: '没有匹配的结果',
  emptyHint: '去市场安装，或创建一个自定义扩展。',
  noResultsHint: '试试其他关键词，或调整类型和来源。',
  browse: '浏览市场',
  removeTitle: '卸载扩展？',
  removeHint:
    '将从当前项目移除，Agent 将无法再使用它。不会删除来源文件或其他客户端的配置，之后可以从市场重新安装。',
  error: '操作失败，请重试。',
  name: '名称',
  description: '用途说明',
  type: '类型',
  permissions: '所需权限',
  version: '版本',
  details: '详情',
  advanced: '高级设置',
  mode: '接入方式',
  command: '可执行命令',
  commandHint: '例如 node、python3 或脚本的绝对路径',
  args: '参数（每行一个）',
  cwd: '工作目录（可选）',
  commandNote:
    '调用参数以 JSON 传入标准输入，标准输出作为结果。安装不会执行命令；调用遵循项目权限审批。',
  httpNote: '调用时向此地址 POST JSON 参数。地址固定，不接受 Agent 改写。',
  endpoint: '服务地址',
  headers: '请求头（JSON，可选）',
  env: '环境变量（JSON，可选）',
  schema: '输入参数（JSON Schema）',
  timeout: '超时（秒）',
  content: '技能内容',
  importFile: '导入 SKILL.md',
  skillNote: '支持完整 SKILL.md，也可以直接编写说明。没有版本时不显示版本。',
  localCommand: '本地命令',
  http: 'HTTP 接口',
  remoteMcp: '远程 MCP',
  connection: '测试连接',
  connected: '连接成功',
  importConfig: '导入 MCP JSON 配置',
  applyConfig: '应用配置',
  required: '请填写名称、用途和对应配置。',
  invalidJson: 'JSON 格式无效，请检查。',
  pickProject: '先打开一个项目，再管理该项目的扩展。',
  localHint:
    '自动发现常用客户端配置。附加目录还支持 synax-tools.json、Skill 目录和 MCP 配置。扫描只读取声明，不执行代码。',
  directories: '附加扫描目录（每行一个，最多 8 个）',
  remoteHint: '远程源是共享目录，安装和启用状态仍属于当前项目。',
  addSource: '添加远程源',
  sourceName: '来源名称',
  sourceId: '来源 ID',
  sourceUrl: '索引 URL / Git 仓库',
  catalog: '扩展清单（工具 / 技能 / MCP）',
  index: 'Skill JSON 索引',
  git: 'Git 仓库',
  sync: '同步',
  deleteSource: '移除来源',
  remoteManifest: '扩展清单格式',
  localManifest: '工具清单格式',
  noVersion: '未提供',
  searchLimit: '远程搜索至少需要 2 个字符。',
  sourceError: '部分来源暂时不可用',
  configImportHint: '粘贴一个 MCP 配置，或只包含一个服务的 mcpServers 对象。',
  testing: '正在测试…',
}
const en: typeof zh = {
  settings: 'Settings',
  extensions: 'Extensions',
  general: 'General',
  archive: 'Session Archive',
  project: 'Project',
  tool: 'Tools',
  skill: 'Skills',
  mcp: 'MCP',
  market: 'Marketplace',
  toolHint: 'Choose the tools your Agent can use in this project.',
  skillHint: 'Reusable knowledge and workflows for this project.',
  mcpHint: 'Connect external services to this project.',
  marketHint: 'Find extensions from built-in, local and remote sources.',
  custom: 'Custom',
  create: 'New extension',
  edit: 'Edit',
  save: 'Save',
  cancel: 'Cancel',
  close: 'Close',
  search: 'Search by name or purpose…',
  clear: 'Clear search',
  allKinds: 'All types',
  allSources: 'All sources',
  source: 'Source',
  sources: 'Manage sources',
  local: 'Local discovery',
  builtin: 'Synax built-in',
  installed: 'Installed',
  toggle: 'Enable',
  enabled: 'Enabled',
  disabled: 'Disabled',
  install: 'Install',
  uninstall: 'Uninstall',
  more: 'More actions',
  refresh: 'Refresh',
  previous: 'Previous',
  next: 'Next',
  loading: 'Loading…',
  empty: 'No extensions yet',
  noResults: 'No matching results',
  emptyHint: 'Install from the marketplace or create a custom extension.',
  noResultsHint: 'Try another keyword, type or source.',
  browse: 'Browse marketplace',
  removeTitle: 'Uninstall extension?',
  removeHint:
    'Remove it from this project so the Agent can no longer use it. Source files and other clients are not changed. You can reinstall it from the marketplace.',
  error: 'Action failed. Please try again.',
  name: 'Name',
  description: 'Purpose',
  type: 'Type',
  permissions: 'Permissions',
  version: 'Version',
  details: 'Details',
  advanced: 'Advanced settings',
  mode: 'Connection',
  command: 'Executable',
  commandHint: 'For example node, python3 or an absolute script path',
  args: 'Arguments (one per line)',
  cwd: 'Working directory (optional)',
  commandNote:
    'Arguments arrive as JSON on stdin; stdout is the result. Installation never executes code. Calls follow project approval rules.',
  httpNote:
    'Calls POST JSON arguments to this fixed URL. The Agent cannot change the endpoint.',
  endpoint: 'Endpoint URL',
  headers: 'Headers (JSON, optional)',
  env: 'Environment (JSON, optional)',
  schema: 'Input parameters (JSON Schema)',
  timeout: 'Timeout (seconds)',
  content: 'Skill content',
  importFile: 'Import SKILL.md',
  skillNote:
    'Use a complete SKILL.md or write plain instructions. Missing versions stay hidden.',
  localCommand: 'Local command',
  http: 'HTTP endpoint',
  remoteMcp: 'Remote MCP',
  connection: 'Test connection',
  connected: 'Connected',
  importConfig: 'Import MCP JSON',
  applyConfig: 'Apply configuration',
  required: 'Provide a name, purpose and matching configuration.',
  invalidJson: 'Invalid JSON. Please check the configuration.',
  pickProject: 'Open a project to manage its extensions.',
  localHint:
    'Discover common client configurations. Extra directories support synax-tools.json, skills and MCP configs. Scanning reads declarations only; it never runs code.',
  directories: 'Extra scan directories (one per line, up to 8)',
  remoteHint:
    'Remote sources are shared catalogs. Installation and enablement remain project-specific.',
  addSource: 'Add remote source',
  sourceName: 'Source name',
  sourceId: 'Source ID',
  sourceUrl: 'Index URL / Git repository',
  catalog: 'Extension catalog (tools / skills / MCP)',
  index: 'Skill JSON index',
  git: 'Git repository',
  sync: 'Sync',
  deleteSource: 'Remove source',
  remoteManifest: 'Extension catalog format',
  localManifest: 'Tool manifest format',
  noVersion: 'Not provided',
  searchLimit: 'Enter at least 2 characters for remote search.',
  sourceError: 'Some sources are unavailable',
  configImportHint:
    'Paste one MCP config or a mcpServers object containing exactly one server.',
  testing: 'Testing…',
}
export function useExtensionCopy() {
  return useLocale().locale === 'zh' ? zh : en
}
export type ExtensionCopy = typeof zh
