import {
  IconBrandAngular,
  IconBrandAstro,
  IconBrandCpp,
  IconBrandCSharp,
  IconBrandCss3,
  IconBrandDeno,
  IconBrandDocker,
  IconBrandGit,
  IconBrandGolang,
  IconBrandGraphql,
  IconBrandHtml5,
  IconBrandJavascript,
  IconBrandKotlin,
  IconBrandNextjs,
  IconBrandNodejs,
  IconBrandNpm,
  IconBrandNuxt,
  IconBrandPhp,
  IconBrandPnpm,
  IconBrandPython,
  IconBrandReact,
  IconBrandRust,
  IconBrandSass,
  IconBrandSvelte,
  IconBrandSwift,
  IconBrandTailwind,
  IconBrandTypescript,
  IconBrandVite,
  IconBrandVue,
  IconBrandYarn,
} from "@tabler/icons-react";
import {
  Database,
  File,
  FileArchive,
  FileHeadphone,
  FileCode,
  FileCog,
  FileImage,
  FileBraces,
  FileSpreadsheet,
  FileTerminal,
  FileText,
  FilePlay,
} from "lucide-react";

// Explicit named imports keep unused icons out of the production bundle.
// Brands use Tabler Outline; formats without a brand use Lucide, never a
// substitute brand or a colored logo. Both families inherit currentColor.
const iconsByExtension = {
  ts: IconBrandTypescript,
  mts: IconBrandTypescript,
  cts: IconBrandTypescript,
  js: IconBrandJavascript,
  mjs: IconBrandJavascript,
  cjs: IconBrandJavascript,
  tsx: IconBrandReact,
  jsx: IconBrandReact,
  vue: IconBrandVue,
  svelte: IconBrandSvelte,
  astro: IconBrandAstro,
  py: IconBrandPython,
  pyw: IconBrandPython,
  pyi: IconBrandPython,
  go: IconBrandGolang,
  rs: IconBrandRust,
  swift: IconBrandSwift,
  kt: IconBrandKotlin,
  kts: IconBrandKotlin,
  cpp: IconBrandCpp,
  cc: IconBrandCpp,
  cxx: IconBrandCpp,
  hpp: IconBrandCpp,
  hxx: IconBrandCpp,
  cs: IconBrandCSharp,
  php: IconBrandPhp,
  html: IconBrandHtml5,
  htm: IconBrandHtml5,
  css: IconBrandCss3,
  scss: IconBrandSass,
  sass: IconBrandSass,
  graphql: IconBrandGraphql,
  gql: IconBrandGraphql,
  c: FileCode,
  h: FileCode,
  java: FileCode,
  rb: FileCode,
  lua: FileCode,
  pl: FileCode,
  r: FileCode,
  dart: FileCode,
  scala: FileCode,
  ex: FileCode,
  exs: FileCode,
  less: FileCode,
  xml: FileCode,
  xsl: FileCode,
  wasm: FileCode,
  json: FileBraces,
  jsonc: FileBraces,
  json5: FileBraces,
  ipynb: FileBraces,
  yaml: FileCog,
  yml: FileCog,
  toml: FileCog,
  ini: FileCog,
  conf: FileCog,
  config: FileCog,
  env: FileCog,
  properties: FileCog,
  md: FileText,
  mdx: FileText,
  markdown: FileText,
  txt: FileText,
  log: FileText,
  pdf: FileText,
  doc: FileText,
  docx: FileText,
  rst: FileText,
  png: FileImage,
  jpg: FileImage,
  jpeg: FileImage,
  gif: FileImage,
  webp: FileImage,
  avif: FileImage,
  svg: FileImage,
  ico: FileImage,
  bmp: FileImage,
  tiff: FileImage,
  tif: FileImage,
  heic: FileImage,
  mp3: FileHeadphone,
  wav: FileHeadphone,
  ogg: FileHeadphone,
  flac: FileHeadphone,
  m4a: FileHeadphone,
  aac: FileHeadphone,
  mp4: FilePlay,
  webm: FilePlay,
  mov: FilePlay,
  avi: FilePlay,
  mkv: FilePlay,
  zip: FileArchive,
  gz: FileArchive,
  tar: FileArchive,
  tgz: FileArchive,
  bz2: FileArchive,
  xz: FileArchive,
  rar: FileArchive,
  "7z": FileArchive,
  csv: FileSpreadsheet,
  tsv: FileSpreadsheet,
  xls: FileSpreadsheet,
  xlsx: FileSpreadsheet,
  ods: FileSpreadsheet,
  sql: Database,
  db: Database,
  sqlite: Database,
  sqlite3: Database,
  sh: FileTerminal,
  bash: FileTerminal,
  zsh: FileTerminal,
  fish: FileTerminal,
  ps1: FileTerminal,
  bat: FileTerminal,
  cmd: FileTerminal,
};

type FileTypeIconComponent =
  (typeof iconsByExtension)[keyof typeof iconsByExtension];

const iconsByName: Record<string, FileTypeIconComponent> = {
  "package.json": IconBrandNpm,
  "package-lock.json": IconBrandNpm,
  "npm-shrinkwrap.json": IconBrandNpm,
  ".npmrc": IconBrandNpm,
  "yarn.lock": IconBrandYarn,
  ".yarnrc": IconBrandYarn,
  ".yarnrc.yml": IconBrandYarn,
  "pnpm-lock.yaml": IconBrandPnpm,
  "pnpm-workspace.yaml": IconBrandPnpm,
  "cargo.toml": IconBrandRust,
  "cargo.lock": IconBrandRust,
  "go.mod": IconBrandGolang,
  "go.sum": IconBrandGolang,
  "pyproject.toml": IconBrandPython,
  "requirements.txt": IconBrandPython,
  pipfile: IconBrandPython,
  "pipfile.lock": IconBrandPython,
  "poetry.lock": IconBrandPython,
  "deno.json": IconBrandDeno,
  "deno.jsonc": IconBrandDeno,
  "deno.lock": IconBrandDeno,
  ".nvmrc": IconBrandNodejs,
  ".node-version": IconBrandNodejs,
  ".gitignore": IconBrandGit,
  ".gitattributes": IconBrandGit,
  ".gitmodules": IconBrandGit,
  ".gitconfig": IconBrandGit,
  dockerfile: IconBrandDocker,
  containerfile: IconBrandDocker,
  ".dockerignore": IconBrandDocker,
  "docker-compose.yml": IconBrandDocker,
  "docker-compose.yaml": IconBrandDocker,
  "compose.yml": IconBrandDocker,
  "compose.yaml": IconBrandDocker,
  "angular.json": IconBrandAngular,
  makefile: FileTerminal,
  justfile: FileTerminal,
  license: FileText,
  licence: FileText,
  readme: FileText,
};

const configIcons: [RegExp, FileTypeIconComponent][] = [
  [/^tsconfig(?:\.[^.]+)*\.json$/, IconBrandTypescript],
  [/^jsconfig(?:\.[^.]+)*\.json$/, IconBrandJavascript],
  [/^vite\.config\.[cm]?[jt]s$/, IconBrandVite],
  [/^next\.config\.[cm]?[jt]s$/, IconBrandNextjs],
  [/^nuxt\.config\.[cm]?[jt]s$/, IconBrandNuxt],
  [/^svelte\.config\.[cm]?[jt]s$/, IconBrandSvelte],
  [/^astro\.config\.[cm]?[jt]s$/, IconBrandAstro],
  [/^vue\.config\.[cm]?[jt]s$/, IconBrandVue],
  [/^tailwind\.config\.[cm]?[jt]s$/, IconBrandTailwind],
  [
    /^(?:(?:dockerfile|containerfile)\..+|.+\.(?:dockerfile|containerfile))$/,
    IconBrandDocker,
  ],
  [/^(?:docker-)?compose\.[^.]+\.ya?ml$/, IconBrandDocker],
  [/^\.env(?:\..+)?$/, FileCog],
];

/** File-name/config matches take precedence over the generic extension. */
export function fileTypeIconForName(fileName: string): FileTypeIconComponent {
  const name = fileName.toLowerCase();
  if (Object.prototype.hasOwnProperty.call(iconsByName, name))
    return iconsByName[name];
  for (const [pattern, Icon] of configIcons) {
    if (pattern.test(name)) return Icon;
  }
  const extension = name.includes(".")
    ? name.slice(name.lastIndexOf(".") + 1)
    : "";
  return Object.prototype.hasOwnProperty.call(iconsByExtension, extension)
    ? iconsByExtension[extension as keyof typeof iconsByExtension]
    : File;
}
