/**
 * Wiki Page — Project knowledge base with auto-generation
 *
 * Not a static wiki. Each page is linked to requirements, ADRs, tasks, and
 * code. The Wiki Agent auto-generates and updates pages from PRs, decisions,
 * and code changes.
 */

import { useState } from 'react'
import { cn } from '../lib/utils'
import {
  BookOpen, Plus, Search, Bot, Link2, Clock,
  FileText, GitPullRequest, AlertCircle, ChevronRight,
} from 'lucide-react'

interface WikiPageData {
  id: string
  title: string
  category: 'guide' | 'api' | 'decision' | 'runbook' | 'onboarding'
  lastUpdated: string
  updatedBy: string
  updatedByKind: 'agent' | 'human'
  autoGenerated: boolean
  linkedReqs: string[]
  linkedAdrs: string[]
  linkedTasks: string[]
  content: string
  needsUpdate: boolean
}

const WIKI_PAGES: WikiPageData[] = [
  {
    id: 'w1', title: '项目概览', category: 'guide',
    lastUpdated: '2h ago', updatedBy: 'Wiki Agent', updatedByKind: 'agent',
    autoGenerated: false, linkedReqs: [], linkedAdrs: [], linkedTasks: [],
    content: `# Synapse 项目概览\n\n## 产品定位\nSynapse 是一个 Agent 驱动的项目管理平台，核心创新是让 AI Agent 和人类在同一个角色体系中协作。\n\n## 核心概念\n- **Role Slot**: 角色槽位，支持 Human ↔ Agent 热切换\n- **Code-First State**: 项目状态从 Git 活动推导\n- **Zero-Alignment Protocol**: 角色化信息投递消除对齐成本\n\n## 团队\n| 角色 | 成员 | 类型 |\n|------|------|------|\n| PM | PM Agent | AI (L3) |\n| Developer | Alice | Human |\n| QA | QA Agent | AI (L2) |`,
    needsUpdate: false,
  },
  {
    id: 'w2', title: 'API 参考 — 认证模块', category: 'api',
    lastUpdated: '1h ago', updatedBy: 'Wiki Agent', updatedByKind: 'agent',
    autoGenerated: true, linkedReqs: ['REQ-003'], linkedAdrs: ['ADR-005'], linkedTasks: ['T5'],
    content: `# 认证模块 API\n\n\`\`\`POST /api/auth/refresh\`\`\`\n\n刷新认证令牌。\n\n**Request:**\n\`\`\`json\n{ "refresh_token": "string" }\n\`\`\`\n\n**Response:**\n\`\`\`json\n{ "access_token": "string", "expires_in": 3600 }\n\`\`\`\n\n> ⚠️ Auto-generated from PR #42. Verify before using in production.`,
    needsUpdate: false,
  },
  {
    id: 'w3', title: '部署运维手册', category: 'runbook',
    lastUpdated: '3d ago', updatedBy: 'DevOps Agent', updatedByKind: 'agent',
    autoGenerated: false, linkedReqs: [], linkedAdrs: ['ADR-003'], linkedTasks: ['T10'],
    content: `# 部署运维手册\n\n## 环境变量\n| 变量 | 说明 | 示例 |\n|------|------|------|\n| DATABASE_URL | 数据库连接 | postgres://... |\n| JWT_SECRET | JWT 签名密钥 | (from vault) |\n\n## 部署流程\n1. CI 通过后自动部署到 staging\n2. 手动审批后部署到 production\n3. 健康检查确认`,
    needsUpdate: false,
  },
  {
    id: 'w4', title: '新手 Onboarding 指南', category: 'onboarding',
    lastUpdated: '1w ago', updatedBy: 'Wiki Agent', updatedByKind: 'agent',
    autoGenerated: true, linkedReqs: [], linkedAdrs: [], linkedTasks: [],
    content: `# 新手 Onboarding\n\n## 第一天\n1. 获取项目访问权限\n2. 阅读《项目概览》wiki\n3. 了解角色分配和 Agent 工作方式\n\n## 第一周\n- 完成首个任务\n- 体验 Agent 协作流程\n- 记录反馈到 Memory`,
    needsUpdate: false,
  },
  {
    id: 'w5', title: '系统架构设计', category: 'decision',
    lastUpdated: '5h ago', updatedBy: 'Alice', updatedByKind: 'human',
    autoGenerated: false, linkedReqs: ['REQ-001'], linkedAdrs: ['ADR-001', 'ADR-002'], linkedTasks: ['T1', 'T2'],
    content: `# 系统架构设计\n\n## 技术栈\n- Frontend: React + Vite + Tailwind\n- Backend: Hono + Node.js\n- Database: SQLite + Drizzle ORM\n- Agent: Python (LangGraph)\n\n## 核心模块\n- Agent Loop Engine\n- Role Slot System\n- Event Bus + Information Broker\n- Code-First State Engine`,
    needsUpdate: true,
  },
]

const CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'guide', label: 'Guides' },
  { id: 'api', label: 'API Ref' },
  { id: 'decision', label: 'Decisions' },
  { id: 'runbook', label: 'Runbooks' },
  { id: 'onboarding', label: 'Onboarding' },
]

const CATEGORY_COLORS: Record<string, string> = {
  guide: 'text-wiki',
  api: 'text-arch',
  decision: 'text-primary',
  runbook: 'text-warning',
  onboarding: 'text-agent',
}

export function WikiPage() {
  const [selectedPage, setSelectedPage] = useState<WikiPageData | null>(WIKI_PAGES[0])
  const [filter, setFilter] = useState('all')
  const [searchQuery, setSearchQuery] = useState('')

  const filteredPages = WIKI_PAGES.filter(p => {
    if (filter !== 'all' && p.category !== filter) return false
    if (searchQuery && !p.title.toLowerCase().includes(searchQuery.toLowerCase())) return false
    return true
  })

  return (
    <div className="flex h-full">
      {/* Page List */}
      <div className="w-64 flex-shrink-0 border-r border-border flex flex-col">
        <div className="h-11 flex items-center gap-2 px-4 border-b border-border">
          <BookOpen size={14} className="text-wiki" />
          <span className="text-xs font-medium">Wiki</span>
          <button className="ml-auto w-6 h-6 rounded flex items-center justify-center hover:bg-secondary text-muted-foreground hover:text-foreground transition-colors">
            <Plus size={12} />
          </button>
        </div>

        {/* Search */}
        <div className="px-3 py-2 border-b border-border">
          <div className="flex items-center gap-2 px-2 py-1.5 rounded-md bg-secondary">
            <Search size={12} className="text-muted-foreground" />
            <input
              value={searchQuery}
              onChange={e => setSearchQuery(e.target.value)}
              placeholder="Search pages..."
              className="flex-1 bg-transparent text-xs outline-none placeholder:text-muted-foreground"
            />
          </div>
        </div>

        {/* Category filters */}
        <div className="px-3 py-2 flex flex-wrap gap-1 border-b border-border">
          {CATEGORIES.map(c => (
            <button
              key={c.id}
              onClick={() => setFilter(c.id)}
              className={cn(
                'text-[10px] font-mono px-1.5 py-0.5 rounded transition-colors',
                filter === c.id ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:text-foreground',
              )}
            >
              {c.label}
            </button>
          ))}
        </div>

        {/* Page list */}
        <div className="flex-1 overflow-auto py-1">
          {filteredPages.map(page => (
            <button
              key={page.id}
              onClick={() => setSelectedPage(page)}
              className={cn(
                'w-full text-left px-4 py-2.5 hover:bg-secondary transition-colors',
                selectedPage?.id === page.id && 'bg-primary/5 border-l-2 border-l-wiki',
              )}
            >
              <div className="flex items-center gap-1.5 mb-0.5">
                <span className={cn('text-[10px] font-mono', CATEGORY_COLORS[page.category])}>
                  {page.category}
                </span>
                {page.autoGenerated && (
                  <span className="text-[8px] font-mono px-1 py-0.5 rounded bg-agent/10 text-agent">AUTO</span>
                )}
                {page.needsUpdate && (
                  <AlertCircle size={10} className="text-warning" />
                )}
              </div>
              <div className="text-xs">{page.title}</div>
              <div className="text-[10px] text-muted-foreground font-mono mt-0.5">
                {page.lastUpdated} by {page.updatedBy}
              </div>
            </button>
          ))}
        </div>
      </div>

      {/* Content Area */}
      {selectedPage ? (
        <div className="flex-1 overflow-auto">
          {/* Breadcrumb + Meta */}
          <div className="h-11 flex items-center justify-between px-6 border-b border-border">
            <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
              <span className="font-mono">{selectedPage.category}</span>
              <ChevronRight size={10} />
              <span className="text-foreground">{selectedPage.title}</span>
            </div>
            <div className="flex items-center gap-3">
              {/* Trace links */}
              {selectedPage.linkedReqs.length > 0 && (
                <div className="flex items-center gap-1">
                  <Link2 size={10} className="text-req" />
                  {selectedPage.linkedReqs.map(r => (
                    <span key={r} className="text-[10px] font-mono text-req">{r}</span>
                  ))}
                </div>
              )}
              {selectedPage.linkedAdrs.length > 0 && (
                <div className="flex items-center gap-1">
                  <Link2 size={10} className="text-arch" />
                  {selectedPage.linkedAdrs.map(r => (
                    <span key={r} className="text-[10px] font-mono text-arch">{r}</span>
                  ))}
                </div>
              )}
              {selectedPage.linkedTasks.length > 0 && (
                <div className="flex items-center gap-1">
                  <Link2 size={10} className="text-primary" />
                  {selectedPage.linkedTasks.map(r => (
                    <span key={r} className="text-[10px] font-mono text-primary">{r}</span>
                  ))}
                </div>
              )}
              {selectedPage.autoGenerated && (
                <span className="flex items-center gap-1 text-[10px] font-mono text-agent">
                  <Bot size={10} /> Auto-generated
                </span>
              )}
              {selectedPage.needsUpdate && (
                <span className="flex items-center gap-1 text-[10px] font-mono text-warning">
                  <AlertCircle size={10} /> Needs update
                </span>
              )}
            </div>
          </div>

          {/* Wiki Content */}
          <div className="max-w-3xl mx-auto px-8 py-8">
            {selectedPage.needsUpdate && (
              <div className="mb-6 px-4 py-3 rounded-lg bg-warning/5 border border-warning/20 flex items-center gap-3">
                <AlertCircle size={16} className="text-warning flex-shrink-0" />
                <div>
                  <div className="text-xs font-medium text-warning mb-0.5">Content may be outdated</div>
                  <div className="text-xs text-muted-foreground">
                    Wiki Agent detected changes in linked PRs/ADRs. Ask the agent to auto-update this page.
                  </div>
                </div>
                <button className="ml-auto flex-shrink-0 text-[10px] font-mono px-2 py-1 rounded bg-agent/10 text-agent hover:bg-agent/20 transition-colors">
                  Auto-update
                </button>
              </div>
            )}

            <div
              className="prose-block"
              dangerouslySetInnerHTML={{
                __html: renderMarkdown(selectedPage.content),
              }}
            />
          </div>
        </div>
      ) : (
        <div className="flex-1 flex items-center justify-center text-sm text-muted-foreground">
          Select a page or create a new one
        </div>
      )}
    </div>
  )
}

// ─── Simple Markdown Renderer ─────────────────────────────────────────────

function renderMarkdown(md: string): string {
  return md
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    .replace(/```(\w+)?\n([\s\S]*?)```/g, '<pre><code>$2</code></pre>')
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/^> (.+)$/gm, '<blockquote>$1</blockquote>')
    .replace(/^\| (.+) \|$/gm, (match) => {
      const cells = match.slice(1, -1).split('|').map(c => c.trim())
      return '<tr>' + cells.map(c => `<td class="px-3 py-1.5 text-xs border border-border">${c}</td>`).join('') + '</tr>'
    })
    .replace(/^\|-+.*$/gm, '')
    .replace(/(<tr>.*<\/tr>\n?)+/g, '<table class="w-full border-collapse mb-3">$&</table>')
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    .replace(/(<li>.*<\/li>\n?)+/g, '<ul class="mb-2">$&</ul>')
    .replace(/^\d+\. (.+)$/gm, '<li>$1</li>')
    .replace(/\n\n/g, '</p><p>')
    .replace(/\n/g, '<br/>')
}
